Prints to main function second revision
briana-mcn/rock-paper-scissors pull request #17
Opened 2017-06-21 19:42 UTC by briana-mcn

Fixes #11 move print functions from`Game` class to main function

2017-06-21 19:47 UTC, briana-mcn commented
@TylerHendrickson here's what I've got so far. I decided to split up the the original `Game.print_players_menu` into their own functions as I thought printing both the the players input and score would be following modularity more closely.

2017-06-21 20:47 UTC, briana-mcn commented
@TylerHendrickson I moved `players_input` and `players_score` methods to functions in `command_line_rock_paper_scissors.py` per our conversation on Slack

2017-06-21 21:03 UTC, briana-mcn commented
@TylerHendrickson I reformatted the `return`ed strings in Game.play and Game.determine_winner for improved modularity (I think that is the word for the reason :) )

2017-06-22 23:45 UTC, TylerHendrickson requested changes
@briana-mcn I have two pretty trivial changes to request, but otherwise no complaints.

2017-06-22 23:45 UTC, TylerHendrickson commented on command_line_rock_paper_scissors.py
> +        players_input_store.append('{} {}: {}'.format(player.name, 'Input', player.choice))
Since the second argument to `format` is always going to be `'Input'` now, it makes more sense to put it in the string template instead.

2017-06-22 23:45 UTC, TylerHendrickson commented on command_line_rock_paper_scissors.py
> +        players_score_store.append('{} {}: {}'.format(player.name, 'Score', player.score))
Same as above

2017-06-23 16:10 UTC, briana-mcn commented
@TylerHendrickson I went ahead and made those changes!

2017-06-23 16:26 UTC, TylerHendrickson approved these changes
@briana-mcn Looks good to me! Approved.

2017-06-23 16:32 UTC, merged